<a href="https://colab.research.google.com/github/adeshshah2912/DS_Python/blob/main/Assignment_17_SVM_Salary_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# SVM Classification
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.preprocessing import StandardScaler

from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn import preprocessing


from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score

In [2]:
df1 = pd.read_csv('/content/SalaryData_Train(1).csv')
df2 = pd.read_csv('/content/SalaryData_Test(1).csv')


In [3]:
df1.head()

age          workclass   education  ...  hoursperweek          native  Salary
0   39          State-gov   Bachelors  ...            40   United-States   <=50K
1   50   Self-emp-not-inc   Bachelors  ...            13   United-States   <=50K
2   38            Private     HS-grad  ...            40   United-States   <=50K
3   53            Private        11th  ...            40   United-States   <=50K
4   28            Private   Bachelors  ...            40            Cuba   <=50K

[5 rows x 14 columns]

In [4]:
label_encoder = preprocessing.LabelEncoder()
df1['workclass']= label_encoder.fit_transform(df1['workclass'])
df1['education']= label_encoder.fit_transform(df1['education'])
df1['maritalstatus']= label_encoder.fit_transform(df1['maritalstatus'])
df1['occupation']= label_encoder.fit_transform(df1['occupation'])
df1['relationship']= label_encoder.fit_transform(df1['relationship'])
df1['race']= label_encoder.fit_transform(df1['race'])
df1['sex']= label_encoder.fit_transform(df1['sex'])
df1['native']= label_encoder.fit_transform(df1['native'])
df1['Salary']= label_encoder.fit_transform(df1['Salary'])

In [5]:
label_encoder = preprocessing.LabelEncoder()
df2['workclass']= label_encoder.fit_transform(df2['workclass'])
df2['education']= label_encoder.fit_transform(df2['education'])
df2['maritalstatus']= label_encoder.fit_transform(df2['maritalstatus'])
df2['occupation']= label_encoder.fit_transform(df2['occupation'])
df2['relationship']= label_encoder.fit_transform(df2['relationship'])
df2['race']= label_encoder.fit_transform(df2['race'])
df2['sex']= label_encoder.fit_transform(df2['sex'])
df2['native']= label_encoder.fit_transform(df2['native'])
df2['Salary']= label_encoder.fit_transform(df2['Salary'])

In [6]:
df1.head()

age  workclass  education  ...  hoursperweek  native  Salary
0   39          5          9  ...            40      37       0
1   50          4          9  ...            13      37       0
2   38          2         11  ...            40      37       0
3   53          2          1  ...            40      37       0
4   28          2          9  ...            40       4       0

[5 rows x 14 columns]

In [7]:
df1.Salary.value_counts()

0    22653
1     7508
Name: Salary, dtype: int64

In [9]:
x = df1.iloc[:,0:13]

In [10]:
# Standardization
a = StandardScaler()
a.fit(x)
X_standardized = a.transform(x)

In [11]:
X_standardized

array([[ 0.04277892,  2.93594688, -0.34982703, ..., -0.21850808,
        -0.07773541,  0.26635842],
       [ 0.88026081,  1.88764517, -0.34982703, ..., -0.21850808,
        -2.33149486,  0.26635842],
       [-0.0333558 , -0.20895825,  0.1748048 , ..., -0.21850808,
        -0.07773541,  0.26635842],
       ...,
       [ 1.48933854, -0.20895825,  0.1748048 , ..., -0.21850808,
        -0.07773541,  0.26635842],
       [-1.25151126, -0.20895825,  0.1748048 , ..., -0.21850808,
        -1.74718685,  0.26635842],
       [ 1.03253024,  0.83934346,  0.1748048 , ..., -0.21850808,
        -0.07773541,  0.26635842]])

In [12]:
y = df2.iloc[:,0:13]

In [13]:
a.fit(y)
Y_standardized = a.transform(y)

In [14]:
Y_standardized

array([[-1.02900513, -0.222347  , -2.42343884, ..., -0.2191694 ,
        -0.07888904,  0.26058067],
       [-0.05742253, -0.222347  ,  0.19017232, ..., -0.2191694 ,
         0.75013125,  0.26058067],
       [-0.80479376, -1.25712632, -0.85527215, ..., -0.2191694 ,
        -0.07888904,  0.26058067],
       ...,
       [-0.05742253, -0.222347  , -0.33254991, ..., -0.2191694 ,
         0.75013125,  0.26058067],
       [ 0.39100021, -0.222347  , -0.33254991, ..., -0.2191694 ,
        -0.07888904,  0.26058067],
       [-0.2816339 ,  0.81243231, -0.33254991, ..., -0.2191694 ,
         1.57915155,  0.26058067]])

In [15]:
array1 = df1.values
array2 = df2.values
X_train = X_standardized
Y_train= array1[:,13]
X_test = Y_standardized
Y_test = array2[:,13]

In [18]:
Y_train

array([0, 0, 0, ..., 0, 0, 1])

**Grid Search CV**

In [19]:
clf = SVC()
param_grid = [{'kernel':['rbf'],'gamma':[50],'C':[0.1] }]
gsv = GridSearchCV(clf,param_grid,cv=10)
gsv.fit(X_train,Y_train)

GridSearchCV(cv=10, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'C': [0.1], 'gamma': [50], 'kernel': ['rbf']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [20]:
gsv.best_params_ , gsv.best_score_ 

({'C': 0.1, 'gamma': 50, 'kernel': 'rbf'}, 0.7515997323741944)

In [21]:
clf = SVC(C= 0.1, gamma = 50)
clf.fit(X_train , Y_train)
y_pred = clf.predict(X_test)
acc = accuracy_score(Y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(Y_test, y_pred)

Accuracy = 75.46480743691899


array([[11358,     2],
       [ 3693,     7]])